export const Action=[
    {
        IdAction : 1,
        titre :'action1',
        date : '12/10/2023',
        lieu : 'algo ',
        type: "culturel",
    },
    {   IdAction : 2,
        titre :'action2',
        date : '12/10/2023',
        lieu : 'algo ',
        type: "culturel",
    },  
    {   IdAction : 3,
        titre :'action3',
        date : '12/10/2023',
        lieu : 'algo ',
        type: "culturel",
    },  
    {   IdAction : 4,
        titre :'action4',
        date : '12/10/2023',
        lieu : 'algo ',
        type: "culturel",
    },  
    {   IdAction : 5,
        titre :'action5',
        date : '12/10/2023',
        lieu : 'algo ',
        type: "culturel",
    },  
    {   IdAction : 6,
        titre :'action6',
        date : '12/10/2023',
        lieu : 'algo ',
        type: "culturel",
    },
]