export const Action=[
    {
        IdAction : 1,
        titre :'action1',
        date : '12/10/2023',
        description : "hello world   Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis quidem iusto dolores ullam quo alias ab dolore.Minima quia dolor possimus, quo odio mollitia itaque autem, ipsam eius, quasi error. v  Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis quidem iusto dolores ullam quo alias ab dolore. Minima quia dolor possimus, quo odio mollitia itaque autem, ipsam eius, quasi error. Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis quidem iusto dolores ullam quo alias ab dolore.Minima quia dolor possimus, quo odio mollitia itaque autem, ipsam eius, quasi error. v  Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis quidem iusto dolores ullam quo alias ab dolore. Minima quia dolor possimus, quo odio mollitia itaque autem, ipsam eius, quasi error Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis quidem iusto dolores ullam quo alias ab dolore.Minima quia dolor possimus, quo odio mollitia itaque autem, ipsam eius, quasi error. v  Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis quidem iusto dolores ullam quo alias ab dolore. Minima quia dolor possimus, quo odio mollitia itaque autem, ipsam eius, quasi error Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis quidem iusto dolores ullam quo alias ab dolore.Minima quia dolor possimus, quo odio mollitia itaque autem, ipsam eius, quasi error. v  Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis quidem iusto dolores ullam quo alias ab dolore. Minima quia dolor possimus, quo odio mollitia itaque autem, ipsam eius, quasi error",
        lieu : 'algo ',
        type: "culturel",
        URl : "assets/images/1.jpg"
    },
    {   IdAction : 2,
        titre :'action2',
        description : "hello world",
        date : '12/10/2023',
        lieu : 'algo ',
        type: "culturel",
        URl : "assets/images/2.jpg"
    },  
    {   IdAction : 3,
        titre :'action3',
        date : '12/10/2023',
        description : "hello world",
        lieu : 'algo ',
        type: "culturel",
        URl : "assets/images/12.jpg"
    },  
    {   IdAction : 4,
        titre :'action4',
        date : '12/10/2023',
        description : "hello world",
        lieu : 'algo ',
        type: "culturel",
        URl : "assets/images/3.jpg"
    },  
    {   IdAction : 5,
        titre :'action5',
        date : '12/10/2023',
        description : "hello world",
        lieu : 'algo ',
        type: "culturel",
        URl : "assets/images/4.jpg"
    },  
    {   IdAction : 6,
        titre :'action6',
        date : '12/10/2023',
        description : "hello world",
        lieu : 'algo ',
        type: "culturel",
        URl : "assets/images/13.jpg"
    },
]